### ISSUE TITLE
Game archive?

### ISSUE THREAD

**Issue by ryanfantus** [lagergren/rylween-regfile-generator#1]
Hi, do you know where I can find the game archive? I have googled and come up short. Thanks!

**Comment by lagergren** [comment]
It seems @bigfug has taken care of that now! There is a zip file in the root directory of the repo now. 

Do you want to tell me a little bit about how you knew about Rylween and your experiences with it? I think it's amazing that people are still doing stuff with this little game in 2023, and I have actually started porting it to a standalone ncurses based kind of thing, including making the game world (which is pretty hard coded), totally configurable.

**Comment by ryanfantus** [comment]
Awesome, thanks!

I actually only recently discovered Rylween. I've always been a fan of roguelikes but recently saw the game on a Zeus BBS and thought it was cool. Then I noticed this repo :)

**Comment by lagergren** [comment]
It was amazing how much people loved this game and how much time they spent on it. I have recovered some of the source, and the rest can be decompiled (sort of), I have a 68xxx disassembler now, and it's not incredibly hard to decompile memory getters and setters given that I know what the structs look like, so I sort of have all the world in a json file now, and whenever I have a free moment I will start adding a portable playable version with source code...  But for some reason now that I thought I was work free for a while, I seem to be involved in two startups, so I have to sort that out because this is a project I would love to do!
